DROP TABLE IF EXISTS tweagle.twitter_users;
CREATE TABLE tweagle.twitter_users (

ac_name VARCHAR(25) NOT NULL,
ac_password VARCHAR(10) NOT NULL,
ac_email VARCHAR(45) NOT NULL,
ac_status BOOLEAN NOT NULL DEFAULT 0,
male BOOLEAN NOT NULL,
creation_date DATE NOT NULL,
last_update_day INT NOT NULL DEFAULT -1,

messages INT NOT NULL DEFAULT 0,
following INT NOT NULL DEFAULT 0,
followers INT NOT NULL DEFAULT 0,

is_tweet BOOLEAN NOT NULL DEFAULT 0,
cur_tweet INT NOT NULL DEFAULT 0,
max_tweet INT NOT NULL DEFAULT 0,
next_tweet BIGINT NOT NULL DEFAULT 0,

is_mention BOOLEAN NOT NULL DEFAULT 0,
cur_mention INT NOT NULL DEFAULT 0,
max_mention INT NOT NULL DEFAULT 0,
next_mention BIGINT NOT NULL DEFAULT 0,

is_retweet BOOLEAN NOT NULL DEFAULT 0,
cur_retweet INT NOT NULL DEFAULT 0,
max_retweet INT NOT NULL DEFAULT 0,
next_retweet BIGINT NOT NULL DEFAULT 0,

is_dm BOOLEAN NOT NULL DEFAULT 0,
cur_dm INT NOT NULL DEFAULT 0,
max_dm INT NOT NULL DEFAULT 0,
next_dm BIGINT NOT NULL DEFAULT 0,

is_follow BOOLEAN NOT NULL DEFAULT 0,
cur_follow INT NOT NULL DEFAULT 0,
max_follow INT NOT NULL DEFAULT 0,
next_follow BIGINT NOT NULL DEFAULT 0,

is_followback BOOLEAN NOT NULL DEFAULT 0,
cur_followback INT NOT NULL DEFAULT 0,
max_followback INT NOT NULL DEFAULT 0,
next_followback BIGINT NOT NULL DEFAULT 0,

is_unfollow BOOLEAN NOT NULL DEFAULT 0,
cur_unfollow INT NOT NULL DEFAULT 0,
max_unfollow INT NOT NULL DEFAULT 0,
next_unfollow BIGINT NOT NULL DEFAULT 0,

is_change_text_status BOOLEAN NOT NULL DEFAULT 0,
next_change_text_status BIGINT NOT NULL DEFAULT 0,

consumer_key VARCHAR(70) NOT NULL DEFAULT '',
consumer_secret VARCHAR(70) NOT NULL DEFAULT '',
access_token VARCHAR(70) NOT NULL DEFAULT '',
access_token_secret VARCHAR(70) NOT NULL DEFAULT '',

PRIMARY KEY (ac_name)
);